# This file was generated by GoReleaser. DO NOT EDIT.
cask "zs-node" do
  version "0.16.0"

  on_macos do
    sha256 "0056ef274990ff4e7e815121d357e08b21e4a00f8871c155aacef6a83c52865f"
    url "https://github.com/txnlab/zs-node/releases/download/v#{version}/zs-node_#{version}_darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "98f32d2343542d3c903b1aba9a0a48ece3d0829d67b7afc2f000905dfc5a476c"
      url "https://github.com/txnlab/zs-node/releases/download/v#{version}/zs-node_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "41d552f9f982117445f4098e417598a69dbee4c54cf528feb83e1650e30745cb"
      url "https://github.com/txnlab/zs-node/releases/download/v#{version}/zs-node_#{version}_linux_arm64.tar.gz"
    end
  end

  name "zs-node"
  desc "Operator node for the ZeroSignal.ai private inference network"
  homepage "https://github.com/txnlab/zs-node"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zs-node"

  # No zap stanza required

  caveats <<~EOS
    zs-node needs a config file + signing mnemonic before it can serve — see
    https://docs.zerosignal.ai/operators for setup.

    To run it at login and restart it on failure (Homebrew casks can't use
    `brew services`, which is formula-only):
      zs-node install-service
    It installs + enables a launchd LaunchAgent that runs the node under
    --config with its own path baked in. `zs-node uninstall-service` removes it.
  EOS
end
