# This file was generated by GoReleaser. DO NOT EDIT.
cask "zs-node" do
  version "0.4.0"

  on_macos do
    sha256 "495b406efb49af86687906c6f2119e1dfc5e90b22f8c40b922ace093bd65ecd9"
    url "https://github.com/txnlab/zs-node/releases/download/v#{version}/zs-node_#{version}_darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "a5c9580c9d0c21d2469d03e8fce7d3227cabc9cad9690b1a56731cda69102b71"
      url "https://github.com/txnlab/zs-node/releases/download/v#{version}/zs-node_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "724929fff481318d1e1643a72ac5761ce705e08e091b91890afb9e55e326b6ff"
      url "https://github.com/txnlab/zs-node/releases/download/v#{version}/zs-node_#{version}_linux_arm64.tar.gz"
    end
  end

  name "zs-node"
  desc "Operator node for the ZeroSignal.ai private inference network"
  homepage "https://github.com/txnlab/zs-node"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zs-node"

  # No zap stanza required

  caveats <<~EOS
    zs-node needs a config file + signing mnemonic before it can serve — see
    https://docs.zerosignal.ai/operators for setup.

    To run it at login and restart it on failure (Homebrew casks can't use
    `brew services`, which is formula-only):
      zs-node install-service
    It installs + enables a launchd LaunchAgent that runs the node under
    --config with its own path baked in. `zs-node uninstall-service` removes it.
  EOS
end
