# This file was generated by GoReleaser. DO NOT EDIT.
cask "zs-node" do
  version "0.18.1"

  on_macos do
    sha256 "8f3f7e3d5b12a18e27250417c184b2abeccf3e0db1c4d2b1cf7ef664a7889a82"
    url "https://github.com/txnlab/zs-node/releases/download/v#{version}/zs-node_#{version}_darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "366f9b0a899fb29f285d95e9030707def94d8878ec7f0245da3c4b7e7005845c"
      url "https://github.com/txnlab/zs-node/releases/download/v#{version}/zs-node_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4adc9e3135fb152ba9fe6b56115f760c72a89061a9a459b3938174cded21374f"
      url "https://github.com/txnlab/zs-node/releases/download/v#{version}/zs-node_#{version}_linux_arm64.tar.gz"
    end
  end

  name "zs-node"
  desc "Operator node for the ZeroSignal.ai private inference network"
  homepage "https://github.com/txnlab/zs-node"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zs-node"

  # No zap stanza required

  caveats <<~EOS
    zs-node needs a config file + signing mnemonic before it can serve — see
    https://docs.zerosignal.ai/operators for setup.

    To run it at login and restart it on failure (Homebrew casks can't use
    `brew services`, which is formula-only):
      zs-node install-service
    It installs + enables a launchd LaunchAgent that runs the node under
    --config with its own path baked in. `zs-node uninstall-service` removes it.
  EOS
end
