# This file was generated by GoReleaser. DO NOT EDIT.
cask "zs-proxy" do
  version "0.15.1"

  on_macos do
    sha256 "12d26bf6a61db56d29c9bc907e72afde99bdd19c20f169eb17bf32125127f284"
    url "https://github.com/txnlab/zs-proxy/releases/download/v#{version}/zs-proxy_#{version}_darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "9b344b197a220e286c0e23ebe4496d16fd7f1db3fe350842f8b855f5aadec5ea"
      url "https://github.com/txnlab/zs-proxy/releases/download/v#{version}/zs-proxy_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3ac17d69efa4804cfe54d7f252562943ea4a3ca0937089e34107f9eb73ecbb02"
      url "https://github.com/txnlab/zs-proxy/releases/download/v#{version}/zs-proxy_#{version}_linux_arm64.tar.gz"
    end
  end

  name "zs-proxy"
  desc "Drop-in, private, OpenAI-compatible inference proxy for ZeroSignal.ai"
  homepage "https://github.com/txnlab/zs-proxy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zs-proxy"

  # No zap stanza required

  caveats <<~EOS
    To run zs-proxy at login and restart it on failure (Homebrew casks can't
    use `brew services`, which is formula-only):
      zs-proxy proxy install-service
    It installs + enables a launchd LaunchAgent with the binary's own path
    baked in. `zs-proxy proxy uninstall-service` removes it.
  EOS
end
