# This file was generated by GoReleaser. DO NOT EDIT.
cask "zs-proxy" do
  version "0.13.1"

  on_macos do
    sha256 "20d3f833f60edb16e3689095d260316ea3b89197a92c642cfc256b0304edb722"
    url "https://github.com/txnlab/zs-proxy/releases/download/v#{version}/zs-proxy_#{version}_darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "42d4b9473cfc6dfb85ca58d794e32c1393c6eaa4f3bd109122b3c15410987dcb"
      url "https://github.com/txnlab/zs-proxy/releases/download/v#{version}/zs-proxy_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7fe4605a3b49daf9ee5f593f725f8a0c28bce274bef91177271168d6934c69fe"
      url "https://github.com/txnlab/zs-proxy/releases/download/v#{version}/zs-proxy_#{version}_linux_arm64.tar.gz"
    end
  end

  name "zs-proxy"
  desc "Drop-in, private, OpenAI-compatible inference proxy for ZeroSignal.ai"
  homepage "https://github.com/txnlab/zs-proxy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zs-proxy"

  # No zap stanza required

  caveats <<~EOS
    To run zs-proxy at login and restart it on failure (Homebrew casks can't
    use `brew services`, which is formula-only):
      zs-proxy proxy install-service
    It installs + enables a launchd LaunchAgent with the binary's own path
    baked in. `zs-proxy proxy uninstall-service` removes it.
  EOS
end
