# This file was generated by GoReleaser. DO NOT EDIT.
cask "zs-proxy" do
  version "0.4.1"

  on_macos do
    sha256 "c5ef9cd15674cd092609f7354cde47ad0196460e45be53855ae0e686625cc003"
    url "https://github.com/txnlab/zs-proxy/releases/download/v#{version}/zs-proxy_#{version}_darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "c24cdb20cd43624b9b071b7dcc4ff366284d6fa9d4844aca83c0f68ee078e2c0"
      url "https://github.com/txnlab/zs-proxy/releases/download/v#{version}/zs-proxy_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e3f6155930c81832ca22086628a0e028dfd78358d12258733d0ad5f990870a76"
      url "https://github.com/txnlab/zs-proxy/releases/download/v#{version}/zs-proxy_#{version}_linux_arm64.tar.gz"
    end
  end

  name "zs-proxy"
  desc "Drop-in, private, OpenAI-compatible inference proxy for ZeroSignal.ai"
  homepage "https://github.com/txnlab/zs-proxy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zs-proxy"

  # No zap stanza required

  caveats <<~EOS
    To run zs-proxy at login and restart it on failure (Homebrew casks can't
    use `brew services`, which is formula-only):
      zs-proxy proxy install-service
    It installs + enables a launchd LaunchAgent with the binary's own path
    baked in. `zs-proxy proxy uninstall-service` removes it.
  EOS
end
